/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ola;

/**
 *
 * @author sergi
 */
public class MainRB extends javax.swing.JFrame {

    /**
     * Creates new form RadioButon
     */
    public MainRB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGenero = new javax.swing.ButtonGroup();
        btnOla = new javax.swing.ButtonGroup();
        cbEstudio = new javax.swing.JCheckBox();
        cbxEdad = new javax.swing.JCheckBox();
        jrHombre = new javax.swing.JRadioButton();
        cbxTermino = new javax.swing.JCheckBox();
        jrMujer = new javax.swing.JRadioButton();
        jrGay = new javax.swing.JRadioButton();
        jrGuaymas = new javax.swing.JRadioButton();
        jrEmpalme = new javax.swing.JRadioButton();
        jrSanjose = new javax.swing.JRadioButton();
        btnEnviar = new javax.swing.JButton();
        txaResumen = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbEstudio.setText("Tienes estudios?");
        cbEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstudioActionPerformed(evt);
            }
        });

        cbxEdad.setText("Mayor de edad");
        cbxEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEdadActionPerformed(evt);
            }
        });

        btnGenero.add(jrHombre);
        jrHombre.setText("Hombre");

        cbxTermino.setText("Acepto los terminos y condiciones ");

        btnGenero.add(jrMujer);
        jrMujer.setText("Mujer");

        btnGenero.add(jrGay);
        jrGay.setText("LGBTQ+");

        btnOla.add(jrGuaymas);
        jrGuaymas.setText("Guaymas");

        btnOla.add(jrEmpalme);
        jrEmpalme.setText("Empalme");

        btnOla.add(jrSanjose);
        jrSanjose.setText("San Jose");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(txaResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(229, 229, 229)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbxTermino)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbEstudio)
                                    .addComponent(cbxEdad, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jrGuaymas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jrEmpalme)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jrSanjose))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jrHombre)
                                    .addGap(39, 39, 39)
                                    .addComponent(jrMujer)
                                    .addGap(36, 36, 36)
                                    .addComponent(jrGay)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(cbEstudio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxEdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTermino)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrHombre)
                    .addComponent(jrMujer)
                    .addComponent(jrGay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrGuaymas)
                    .addComponent(jrEmpalme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrSanjose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(txaResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstudioActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        String estudia="";
        String mayoredad="";
        String terminos="";
        String genero="";
        String ciudad="";
        String resumen="";
        if(cbEstudio.isSelected()){
            estudia="Estudia Si";
        }else{
            estudia="Estudia No";
        }
       
        if(cbxEdad.isSelected()){
            mayoredad = "Mayor de edad Si";
        }else{
            mayoredad = "Mayor de edad No";
        }
            if(cbxTermino.isSelected()){
            terminos = "Terminos Acceptados Si";
        }else{
            terminos = "Terminos Acceptados No";
        }
        resumen = estudia+"\n"+mayoredad+"\n"+terminos+"\n";
        
       if(jrGuaymas.isSelected()){
           ciudad = "esta seleccionado Guaymas";
       }else if(jrEmpalme.isSelected()){
           ciudad = "esta seleccionado empalme";
       }else{
           ciudad = "esta seleccionado San jose";
       }
        resumen += ciudad+"\n";
         if(jrHombre.isSelected()){
           genero = "Genero seleccionado : Hombre";
       }else if(jrMujer.isSelected()){
           genero = "Genero seleccionado : Mujer";
       }else{
           genero = "Genero seleccionado : LGBTQ+";
       }
      resumen = estudia+"\n"+mayoredad+"\n"+terminos+"\n"+ciudad+"\n"+genero+"\n";
      txaResumen.setText(resumen);
       
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void cbxEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEdadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainRB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainRB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainRB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainRB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainRB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.ButtonGroup btnGenero;
    private javax.swing.ButtonGroup btnOla;
    private javax.swing.JCheckBox cbEstudio;
    private javax.swing.JCheckBox cbxEdad;
    private javax.swing.JCheckBox cbxTermino;
    private javax.swing.JRadioButton jrEmpalme;
    private javax.swing.JRadioButton jrGay;
    private javax.swing.JRadioButton jrGuaymas;
    private javax.swing.JRadioButton jrHombre;
    private javax.swing.JRadioButton jrMujer;
    private javax.swing.JRadioButton jrSanjose;
    private java.awt.TextArea txaResumen;
    // End of variables declaration//GEN-END:variables
}
